apiVersion: v1
kind: Service
metadata:
  name: {{ include "goatandwolf.fullname" . }}webgoat
  labels:
    {{- include "goatandwolf.labels" . | nindent 4 }}
spec:
  type: {{ .Values.serviceWebGoat.type }}
  ports:
    - port: {{ .Values.serviceWebGoat.port }}
      targetPort: httpwebgoat
      protocol: TCP
      name: http
  selector:
    {{- include "goatandwolf.selectorLabels" . | nindent 4 }}
