apiVersion: v1
kind: Service
metadata:
  name: "{{ include "goatandwolf.fullname" . }}webwolf"
  labels:
    {{- include "goatandwolf.labels" . | nindent 4 }}
spec:
  type: {{ .Values.serviceWebWolf.type }}
  ports:
    - port: {{ .Values.serviceWebWolf.port }}
      targetPort: httpwebwolf
      protocol: TCP
      name: http
  selector:
    {{- include "goatandwolf.selectorLabels" . | nindent 4 }}
